---
title: "Visualizing Cholesterol Data"
author: "Group 3: Sarah Ogden, Nabin L"
date: "2025-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries and Data
```{r}
library(tidyverse)
library(ggplot2)

df <- read_csv("CHOLESTEROL.csv")
head(df)
```

# Data Visualizations
# What proportion of the population has hereditary history of Hypercholesterolemia?
```{r}
library(dplyr)

df <- df %>%
  mutate(Heredity = recode(Heredity, `0` = 'Neither Parent', `1` = 'One Parent', `2` = 'Both Parents'))
head(df)
ggplot(df, aes(x="",fill=Heredity)) +
  geom_bar(position="fill") +
  geom_text(stat='count', 
            aes(y=after_stat(..count..),label=after_stat(..count..)),
            position=position_fill(0.5)) +
  coord_polar(theta="y") +
  theme_void()+
  labs(title="Percentages of Hypercholesterolemia Heredity")
```
# Does Cholesterol differ by Heredity?
```{r} 
ggplot(df,aes(x=Heredity,y=Tot_Chol,color=Heredity))+
  geom_boxplot()+
  expand_limits(y = 0)+
  labs(title="Cholesterol by Heredity",y="Total Cholesterol",x="Parents with Hypercholesterolemia")
```
# How does Cholesterol differ between genders?
```{r}
ggplot(df, aes(x=Gender,y=Tot_Chol,color=Gender))+
  geom_boxplot()+
  expand_limits(y = 0)+
  labs(title="Cholesterol by Gender",y="Total Cholesterol")
```
# What is the relationship between BMI and Cholesterol?
```{r }
df$BMI <- (df$Weight / (df$Height^2)) * 703

plot(df$BMI, df$Tot_Chol, main = "Cholesterol vs BMI", xlab = "BMI", ylab = "Total Cholesterol")
cor(df$BMI, df$Tot_Chol)

ggplot(df, aes(x = Gender, y = Tot_Chol)) +
  geom_boxplot() + 
 labs(title = "Total Cholesterol by Gender", x = "Gender", y= "Total Cholesterol") +
  theme_minimal()


```

# What is the effect of sleep and exercise on Cholesterol?
```{r}
boxplot(Tot_Chol ~ Sleep, data = df, main = "Cholesterol by Sleep", xlab="Sleep", ylab= "Total Cholesterol")

boxplot(Tot_Chol ~ Exercise, data = df, main = "Cholesterol by Exercise", xlab="Exercise", ylab= "Total Cholesterol")

sleep_exercise_model <- lm(Tot_Chol ~ Sleep + Exercise, data = df)
summary(sleep_exercise_model)

```


# Model Fitting
```{r}
library(leaps)
full_model <- lm(Tot_Chol ~., data = df)
summary(full_model)

Best_subset <- regsubsets(Tot_Chol ~., data = df, nbest = 2)
best_summary <- summary(Best_subset)


bs_result <- data.frame(
  NumVar = 1:nrow(best_summary$which),
  best_summary$outmat, 
  RSQ = best_summary$rsq, 
  RSS = best_summary$rss,
  AdjR2 = best_summary$adjr2, 
  CP = best_summary$cp,
  BIC = best_summary$bic)

bs
bs_model = lm(Tot_Chol ~ Gender + Heredity + Smoke + Age + Exercise + BMI, data = df)


anova(full_model, bs_model)


```

